### ISSUE TITLE
Strophe connection handlers are not called after successful rebind.

### ISSUE THREAD

**Issue by deepakbandela** [prefiks/strophe-rebind#1]
after a successful rebind from the chat server. 

I don't see the handlers are not called.

I implicitly called using connection.addHandler() still I don't see them called.

How to fix this?

**Comment by prefiks** [comment]
Hello,

This was fixed by df7e425ca05c475cae1dd991f122f88427acc808, so please get updated strophe.rebind.js files and it should start working.
