### ISSUE TITLE
Strophe.prototype getting null

### ISSUE THREAD

**Issue by deepakbandela** [prefiks/strophe-rebind#2]
In some cases when the rebind has failed I have observed that Strophe.prototype gets null

 Strophe.prototype.authenticate.call(this._conn, mechanisms); crashes with a null pointer exception.

This should smoothly handle a fresh login along with Strophe.

Can you please fix this?

**Comment by prefiks** [comment]
Hello Deepak,

This should be fixed by commit d3e35f6fd7f8177227935cd3cdf063ac7590ff0f, updating from master should give you working version.

**Comment by deepakbandela** [comment]
right I realized after raising the defect. 

Thanks for your fix.
